---
driver:
  name: vagrant
  config:
    require_chef_omnibus: true
  customize:
    memory: 1024
    cpus: 1

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04
  - name: centos-6.6
  - name: centos-7.0

suites:
  - name: default
    run_list:
      - recipe[maven::default]
      - recipe[git::default]
      - recipe[yajsw::default]
    attributes:
